name: Test
on:
  push:
    paths-ignore: 
      - '*.md'

env:
  JAVA_VERSION: 21

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Make Gradle executables
        run: chmod +x ./gradlew
        
      - name: Check Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

  unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: ${{ env.JAVA_VERSION }}
                  
            - name: Make Gradle executable
              run: chmod +x ./gradlew

            - name: Unit tests
              run: ./gradlew test
